site_name: "JSON-LD-Test"

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 2
          show_root_heading: true
          docstring_style: google
          extensions:
          - griffe_pydantic:
              schema: true