[project]
name = "json-ld-test"
version = "0.0.1"
dependencies = [
    
]

[project.optional-dependencies]
dev = ["requests", "black", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"