from json_ld_test.model import ContextTestCase

tests = [
    ContextTestCase(
        input="compact/0001-in.jsonld",
        expect="compact/0001-out.jsonld",
        context="compact/0001-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0002-in.jsonld",
        expect="compact/0002-out.jsonld",
        context="compact/0002-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0003-in.jsonld",
        expect="compact/0003-out.jsonld",
        context="compact/0003-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0004-in.jsonld",
        expect="compact/0004-out.jsonld",
        context="compact/0004-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0005-in.jsonld",
        expect="compact/0005-out.jsonld",
        context="compact/0005-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0006-in.jsonld",
        expect="compact/0006-out.jsonld",
        context="compact/0006-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0007-in.jsonld",
        expect="compact/0007-out.jsonld",
        context="compact/0007-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0008-in.jsonld",
        expect="compact/0008-out.jsonld",
        context="compact/0008-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0009-in.jsonld",
        expect="compact/0009-out.jsonld",
        context="compact/0009-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0010-in.jsonld",
        expect="compact/0010-out.jsonld",
        context="compact/0010-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0011-in.jsonld",
        expect="compact/0011-out.jsonld",
        context="compact/0011-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0012-in.jsonld",
        expect="compact/0012-out.jsonld",
        context="compact/0012-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0013-in.jsonld",
        expect="compact/0013-out.jsonld",
        context="compact/0013-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0014-in.jsonld",
        expect="compact/0014-out.jsonld",
        context="compact/0014-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0015-in.jsonld",
        expect="compact/0015-out.jsonld",
        context="compact/0015-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0016-in.jsonld",
        expect="compact/0016-out.jsonld",
        context="compact/0016-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0017-in.jsonld",
        expect="compact/0017-out.jsonld",
        context="compact/0017-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0018-in.jsonld",
        expect="compact/0018-out.jsonld",
        context="compact/0018-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0019-in.jsonld",
        expect="compact/0019-out.jsonld",
        context="compact/0019-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0020-in.jsonld",
        expect="compact/0020-out.jsonld",
        context="compact/0020-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0021-in.jsonld",
        expect="compact/0021-out.jsonld",
        context="compact/0021-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0022-in.jsonld",
        expect="compact/0022-out.jsonld",
        context="compact/0022-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0023-in.jsonld",
        expect="compact/0023-out.jsonld",
        context="compact/0023-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0024-in.jsonld",
        expect="compact/0024-out.jsonld",
        context="compact/0024-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0025-in.jsonld",
        expect="compact/0025-out.jsonld",
        context="compact/0025-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0026-in.jsonld",
        expect="compact/0026-out.jsonld",
        context="compact/0026-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0027-in.jsonld",
        expect="compact/0027-out.jsonld",
        context="compact/0027-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0028-in.jsonld",
        expect="compact/0028-out.jsonld",
        context="compact/0028-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0029-in.jsonld",
        expect="compact/0029-out.jsonld",
        context="compact/0029-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0030-in.jsonld",
        expect="compact/0030-out.jsonld",
        context="compact/0030-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0031-in.jsonld",
        expect="compact/0031-out.jsonld",
        context="compact/0031-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0032-in.jsonld",
        expect="compact/0032-out.jsonld",
        context="compact/0032-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0033-in.jsonld",
        expect="compact/0033-out.jsonld",
        context="compact/0033-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0034-in.jsonld",
        expect="compact/0034-out.jsonld",
        context="compact/0034-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0035-in.jsonld",
        expect="compact/0035-out.jsonld",
        context="compact/0035-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0036-in.jsonld",
        expect="compact/0036-out.jsonld",
        context="compact/0036-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0037-in.jsonld",
        expect="compact/0037-out.jsonld",
        context="compact/0037-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0038-in.jsonld",
        expect="compact/0038-out.jsonld",
        context="compact/0038-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0038-in.jsonld",
        expect="compact/0038a-out.jsonld",
        context="compact/0038-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0039-in.jsonld",
        expect="compact/0039-out.jsonld",
        context="compact/0039-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0040-in.jsonld",
        expect="compact/0040-out.jsonld",
        context="compact/0040-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0041-in.jsonld",
        expect="compact/0041-out.jsonld",
        context="compact/0041-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0042-in.jsonld",
        expect="compact/0042-out.jsonld",
        context="compact/0042-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0043-in.jsonld",
        expect="compact/0043-out.jsonld",
        context="compact/0043-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0044-in.jsonld",
        expect="compact/0044-out.jsonld",
        context="compact/0044-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0045-in.jsonld",
        expect="compact/0045-out.jsonld",
        context="compact/0045-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0046-in.jsonld",
        expect="compact/0046-out.jsonld",
        context="compact/0046-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0047-in.jsonld",
        expect="compact/0047-out.jsonld",
        context="compact/0047-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0048-in.jsonld",
        expect="compact/0048-out.jsonld",
        context="compact/0048-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0049-in.jsonld",
        expect="compact/0049-out.jsonld",
        context="compact/0049-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0050-in.jsonld",
        expect="compact/0050-out.jsonld",
        context="compact/0050-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0051-in.jsonld",
        expect="compact/0051-out.jsonld",
        context="compact/0051-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0052-in.jsonld",
        expect="compact/0052-out.jsonld",
        context="compact/0052-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0053-in.jsonld",
        expect="compact/0053-out.jsonld",
        context="compact/0053-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0054-in.jsonld",
        expect="compact/0054-out.jsonld",
        context="compact/0054-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0055-in.jsonld",
        expect="compact/0055-out.jsonld",
        context="compact/0055-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0056-in.jsonld",
        expect="compact/0056-out.jsonld",
        context="compact/0056-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0057-in.jsonld",
        expect="compact/0057-out.jsonld",
        context="compact/0057-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0058-in.jsonld",
        expect="compact/0058-out.jsonld",
        context="compact/0058-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0059-in.jsonld",
        expect="compact/0059-out.jsonld",
        context="compact/0059-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0060-in.jsonld",
        expect="compact/0060-out.jsonld",
        context="compact/0060-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0061-in.jsonld",
        expect="compact/0061-out.jsonld",
        context="compact/0061-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0062-in.jsonld",
        expect="compact/0062-out.jsonld",
        context="compact/0062-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0063-in.jsonld",
        expect="compact/0063-out.jsonld",
        context="compact/0063-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0064-in.jsonld",
        expect="compact/0064-out.jsonld",
        context="compact/0064-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0065-in.jsonld",
        expect="compact/0065-out.jsonld",
        context="compact/0065-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0066-in.jsonld",
        expect="compact/0066-out.jsonld",
        context="compact/0066-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0067-in.jsonld",
        expect="compact/0067-out.jsonld",
        context="compact/0067-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0068-in.jsonld",
        expect="compact/0068-out.jsonld",
        context="compact/0068-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0069-in.jsonld",
        expect="compact/0069-out.jsonld",
        context="compact/0069-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0070-in.jsonld",
        expect="compact/0070-out.jsonld",
        context="compact/0070-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0071-in.jsonld",
        expect="compact/0071-out.jsonld",
        context="compact/0071-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0072-in.jsonld",
        expect="compact/0072-out.jsonld",
        context="compact/0072-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0073-in.jsonld",
        expect="compact/0073-out.jsonld",
        context="compact/0073-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0074-in.jsonld",
        expect="compact/0074-out.jsonld",
        context="compact/0074-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0075-in.jsonld",
        expect="compact/0075-out.jsonld",
        context="compact/0075-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0076-in.jsonld",
        expect="compact/0076-out.jsonld",
        context="compact/0076-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0077-in.jsonld",
        expect="compact/0077-out.jsonld",
        context="compact/0077-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0078-in.jsonld",
        expect="compact/0078-out.jsonld",
        context="compact/0078-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0079-in.jsonld",
        expect="compact/0079-out.jsonld",
        context="compact/0079-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0080-in.jsonld",
        expect="compact/0080-out.jsonld",
        context="compact/0080-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0081-in.jsonld",
        expect="compact/0081-out.jsonld",
        context="compact/0081-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0082-in.jsonld",
        expect="compact/0082-out.jsonld",
        context="compact/0082-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0083-in.jsonld",
        expect="compact/0083-out.jsonld",
        context="compact/0083-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0084-in.jsonld",
        expect="compact/0084-out.jsonld",
        context="compact/0084-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0085-in.jsonld",
        expect="compact/0085-out.jsonld",
        context="compact/0085-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0086-in.jsonld",
        expect="compact/0086-out.jsonld",
        context="compact/0086-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0087-in.jsonld",
        expect="compact/0087-out.jsonld",
        context="compact/0087-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0088-in.jsonld",
        expect="compact/0088-out.jsonld",
        context="compact/0088-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0089-in.jsonld",
        expect="compact/0089-out.jsonld",
        context="compact/0089-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0090-in.jsonld",
        expect="compact/0090-out.jsonld",
        context="compact/0090-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0091-in.jsonld",
        expect="compact/0091-out.jsonld",
        context="compact/0091-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0092-in.jsonld",
        expect="compact/0092-out.jsonld",
        context="compact/0092-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0093-in.jsonld",
        expect="compact/0093-out.jsonld",
        context="compact/0093-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0094-in.jsonld",
        expect="compact/0094-out.jsonld",
        context="compact/0094-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0095-in.jsonld",
        expect="compact/0095-out.jsonld",
        context="compact/0095-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0096-in.jsonld",
        expect="compact/0096-out.jsonld",
        context="compact/0096-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0097-in.jsonld",
        expect="compact/0097-out.jsonld",
        context="compact/0097-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0098-in.jsonld",
        expect="compact/0098-out.jsonld",
        context="compact/0098-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0099-in.jsonld",
        expect="compact/0099-out.jsonld",
        context="compact/0099-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0100-in.jsonld",
        expect="compact/0100-out.jsonld",
        context="compact/0100-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0101-in.jsonld",
        expect="compact/0101-out.jsonld",
        context="compact/0101-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0102-in.jsonld",
        expect="compact/0102-out.jsonld",
        context="compact/0102-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0103-in.jsonld",
        expect="compact/0103-out.jsonld",
        context="compact/0103-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0104-in.jsonld",
        expect="compact/0104-out.jsonld",
        context="compact/0104-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0105-in.jsonld",
        expect="compact/0105-out.jsonld",
        context="compact/0105-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0106-in.jsonld",
        expect="compact/0106-out.jsonld",
        context="compact/0106-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0107-in.jsonld",
        expect="compact/0107-out.jsonld",
        context="compact/0107-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0108-in.jsonld",
        expect="compact/0108-out.jsonld",
        context="compact/0108-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0109-in.jsonld",
        expect="compact/0109-out.jsonld",
        context="compact/0109-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0110-in.jsonld",
        expect="compact/0110-out.jsonld",
        context="compact/0110-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0111-in.jsonld",
        expect="compact/0111-out.jsonld",
        context="compact/0111-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0112-in.jsonld",
        expect="compact/0112-out.jsonld",
        context="compact/0112-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0113-in.jsonld",
        expect="compact/0113-out.jsonld",
        context="compact/0113-context.jsonld",
    ),
    ContextTestCase(
        input="compact/0114-in.jsonld",
        expect="compact/0114-out.jsonld",
        context="compact/0114-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c001-in.jsonld",
        expect="compact/c001-out.jsonld",
        context="compact/c001-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c002-in.jsonld",
        expect="compact/c002-out.jsonld",
        context="compact/c002-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c003-in.jsonld",
        expect="compact/c003-out.jsonld",
        context="compact/c003-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c004-in.jsonld",
        expect="compact/c004-out.jsonld",
        context="compact/c004-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c005-in.jsonld",
        expect="compact/c005-out.jsonld",
        context="compact/c005-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c006-in.jsonld",
        expect="compact/c006-out.jsonld",
        context="compact/c006-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c007-in.jsonld",
        expect="compact/c007-out.jsonld",
        context="compact/c007-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c008-in.jsonld",
        expect="compact/c008-out.jsonld",
        context="compact/c008-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c009-in.jsonld",
        expect="compact/c009-out.jsonld",
        context="compact/c009-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c010-in.jsonld",
        expect="compact/c010-out.jsonld",
        context="compact/c010-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c011-in.jsonld",
        expect="compact/c011-out.jsonld",
        context="compact/c011-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c012-in.jsonld",
        expect="compact/c012-out.jsonld",
        context="compact/c012-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c013-in.jsonld",
        expect="compact/c013-out.jsonld",
        context="compact/c013-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c014-in.jsonld",
        expect="compact/c014-out.jsonld",
        context="compact/c014-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c015-in.jsonld",
        expect="compact/c015-out.jsonld",
        context="compact/c015-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c016-in.jsonld",
        expect="compact/c016-out.jsonld",
        context="compact/c016-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c017-in.jsonld",
        expect="compact/c017-out.jsonld",
        context="compact/c017-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c018-in.jsonld",
        expect="compact/c018-out.jsonld",
        context="compact/c018-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c019-in.jsonld",
        expect="compact/c019-out.jsonld",
        context="compact/c019-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c020-in.jsonld",
        expect="compact/c020-out.jsonld",
        context="compact/c020-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c021-in.jsonld",
        expect="compact/c021-out.jsonld",
        context="compact/c021-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c022-in.jsonld",
        expect="compact/c022-out.jsonld",
        context="compact/c022-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c023-in.jsonld",
        expect="compact/c023-out.jsonld",
        context="compact/c023-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c024-in.jsonld",
        expect="compact/c024-out.jsonld",
        context="compact/c024-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c025-in.jsonld",
        expect="compact/c025-out.jsonld",
        context="compact/c025-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c026-in.jsonld",
        expect="compact/c026-out.jsonld",
        context="compact/c026-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c027-in.jsonld",
        expect="compact/c027-out.jsonld",
        context="compact/c027-context.jsonld",
    ),
    ContextTestCase(
        input="compact/c028-in.jsonld",
        expect="compact/c028-out.jsonld",
        context="compact/c028-context.jsonld",
    ),
    ContextTestCase(
        input="compact/di01-in.jsonld",
        expect="compact/di01-out.jsonld",
        context="compact/di01-context.jsonld",
    ),
    ContextTestCase(
        input="compact/di02-in.jsonld",
        expect="compact/di02-out.jsonld",
        context="compact/di02-context.jsonld",
    ),
    ContextTestCase(
        input="compact/di03-in.jsonld",
        expect="compact/di03-out.jsonld",
        context="compact/di03-context.jsonld",
    ),
    ContextTestCase(
        input="compact/di04-in.jsonld",
        expect="compact/di04-out.jsonld",
        context="compact/di04-context.jsonld",
    ),
    ContextTestCase(
        input="compact/di05-in.jsonld",
        expect="compact/di05-out.jsonld",
        context="compact/di05-context.jsonld",
    ),
    ContextTestCase(
        input="compact/di06-in.jsonld",
        expect="compact/di06-out.jsonld",
        context="compact/di06-context.jsonld",
    ),
    ContextTestCase(
        input="compact/di07-in.jsonld",
        expect="compact/di07-out.jsonld",
        context="compact/di07-context.jsonld",
    ),
    ContextTestCase(
        input="compact/e001-in.jsonld", context="compact/e001-context.jsonld"
    ),
    ContextTestCase(
        input="compact/e002-in.jsonld", context="compact/e002-context.jsonld"
    ),
    ContextTestCase(
        input="compact/en01-in.jsonld", context="compact/en01-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep05-in.jsonld", context="compact/ep05-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep06-in.jsonld", context="compact/ep06-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep07-in.jsonld", context="compact/ep07-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep08-in.jsonld", context="compact/ep08-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep09-in.jsonld", context="compact/ep09-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep10-in.jsonld", context="compact/ep10-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep11-in.jsonld", context="compact/ep11-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep12-in.jsonld", context="compact/ep12-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep13-in.jsonld", context="compact/ep13-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep14-in.jsonld", context="compact/ep14-context.jsonld"
    ),
    ContextTestCase(
        input="compact/ep15-in.jsonld", context="compact/ep15-context.jsonld"
    ),
    ContextTestCase(
        input="compact/in01-in.jsonld",
        expect="compact/in01-out.jsonld",
        context="compact/in01-context.jsonld",
    ),
    ContextTestCase(
        input="compact/in02-in.jsonld",
        expect="compact/in02-out.jsonld",
        context="compact/in02-context.jsonld",
    ),
    ContextTestCase(
        input="compact/in03-in.jsonld",
        expect="compact/in03-out.jsonld",
        context="compact/in03-context.jsonld",
    ),
    ContextTestCase(
        input="compact/in04-in.jsonld",
        expect="compact/in04-out.jsonld",
        context="compact/in04-context.jsonld",
    ),
    ContextTestCase(
        input="compact/in05-in.jsonld",
        expect="compact/in05-out.jsonld",
        context="compact/in05-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js01-in.jsonld",
        expect="compact/js01-out.jsonld",
        context="compact/js01-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js02-in.jsonld",
        expect="compact/js02-out.jsonld",
        context="compact/js02-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js03-in.jsonld",
        expect="compact/js03-out.jsonld",
        context="compact/js03-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js04-in.jsonld",
        expect="compact/js04-out.jsonld",
        context="compact/js04-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js05-in.jsonld",
        expect="compact/js05-out.jsonld",
        context="compact/js05-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js06-in.jsonld",
        expect="compact/js06-out.jsonld",
        context="compact/js06-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js07-in.jsonld",
        expect="compact/js07-out.jsonld",
        context="compact/js07-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js08-in.jsonld",
        expect="compact/js08-out.jsonld",
        context="compact/js08-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js09-in.jsonld",
        expect="compact/js09-out.jsonld",
        context="compact/js09-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js10-in.jsonld",
        expect="compact/js10-out.jsonld",
        context="compact/js10-context.jsonld",
    ),
    ContextTestCase(
        input="compact/js11-in.jsonld",
        expect="compact/js11-out.jsonld",
        context="compact/js11-context.jsonld",
    ),
    ContextTestCase(
        input="compact/la01-in.jsonld",
        expect="compact/la01-out.jsonld",
        context="compact/la01-context.jsonld",
    ),
    ContextTestCase(
        input="compact/li01-in.jsonld",
        expect="compact/li01-out.jsonld",
        context="compact/li01-context.jsonld",
    ),
    ContextTestCase(
        input="compact/li02-in.jsonld",
        expect="compact/li02-out.jsonld",
        context="compact/li02-context.jsonld",
    ),
    ContextTestCase(
        input="compact/li03-in.jsonld",
        expect="compact/li03-out.jsonld",
        context="compact/li03-context.jsonld",
    ),
    ContextTestCase(
        input="compact/li04-in.jsonld",
        expect="compact/li04-out.jsonld",
        context="compact/li04-context.jsonld",
    ),
    ContextTestCase(
        input="compact/li05-in.jsonld",
        expect="compact/li05-out.jsonld",
        context="compact/li05-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m001-in.jsonld",
        expect="compact/m001-out.jsonld",
        context="compact/m001-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m002-in.jsonld",
        expect="compact/m002-out.jsonld",
        context="compact/m002-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m003-in.jsonld",
        expect="compact/m003-out.jsonld",
        context="compact/m003-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m004-in.jsonld",
        expect="compact/m004-out.jsonld",
        context="compact/m004-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m005-in.jsonld",
        expect="compact/m005-out.jsonld",
        context="compact/m005-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m006-in.jsonld",
        expect="compact/m006-out.jsonld",
        context="compact/m006-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m007-in.jsonld",
        expect="compact/m007-out.jsonld",
        context="compact/m007-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m008-in.jsonld",
        expect="compact/m008-out.jsonld",
        context="compact/m008-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m009-in.jsonld",
        expect="compact/m009-out.jsonld",
        context="compact/m009-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m010-in.jsonld",
        expect="compact/m010-out.jsonld",
        context="compact/m010-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m011-in.jsonld",
        expect="compact/m011-out.jsonld",
        context="compact/m011-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m012-in.jsonld",
        expect="compact/m012-out.jsonld",
        context="compact/m012-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m013-in.jsonld",
        expect="compact/m013-out.jsonld",
        context="compact/m013-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m014-in.jsonld",
        expect="compact/m014-out.jsonld",
        context="compact/m014-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m015-in.jsonld",
        expect="compact/m015-out.jsonld",
        context="compact/m015-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m016-in.jsonld",
        expect="compact/m016-out.jsonld",
        context="compact/m016-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m017-in.jsonld",
        expect="compact/m017-out.jsonld",
        context="compact/m017-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m018-in.jsonld",
        expect="compact/m018-out.jsonld",
        context="compact/m018-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m019-in.jsonld",
        expect="compact/m019-out.jsonld",
        context="compact/m019-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m020-in.jsonld",
        expect="compact/m020-out.jsonld",
        context="compact/m020-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m021-in.jsonld",
        expect="compact/m021-out.jsonld",
        context="compact/m021-context.jsonld",
    ),
    ContextTestCase(
        input="compact/m022-in.jsonld",
        expect="compact/m022-out.jsonld",
        context="compact/m022-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n001-in.jsonld",
        expect="compact/n001-out.jsonld",
        context="compact/n001-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n002-in.jsonld",
        expect="compact/n002-out.jsonld",
        context="compact/n002-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n003-in.jsonld",
        expect="compact/n003-out.jsonld",
        context="compact/n003-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n004-in.jsonld",
        expect="compact/n004-out.jsonld",
        context="compact/n004-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n005-in.jsonld",
        expect="compact/n005-out.jsonld",
        context="compact/n005-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n006-in.jsonld",
        expect="compact/n006-out.jsonld",
        context="compact/n006-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n007-in.jsonld",
        expect="compact/n007-out.jsonld",
        context="compact/n007-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n008-in.jsonld",
        expect="compact/n008-out.jsonld",
        context="compact/n008-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n009-in.jsonld",
        expect="compact/n009-out.jsonld",
        context="compact/n009-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n010-in.jsonld",
        expect="compact/n010-out.jsonld",
        context="compact/n010-context.jsonld",
    ),
    ContextTestCase(
        input="compact/n011-in.jsonld",
        expect="compact/n011-out.jsonld",
        context="compact/n011-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p001-in.jsonld",
        expect="compact/p001-out.jsonld",
        context="compact/p001-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p002-in.jsonld",
        expect="compact/p002-out.jsonld",
        context="compact/p002-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p003-in.jsonld",
        expect="compact/p003-out.jsonld",
        context="compact/p003-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p004-in.jsonld",
        expect="compact/p004-out.jsonld",
        context="compact/p004-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p005-in.jsonld",
        expect="compact/p005-out.jsonld",
        context="compact/p005-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p006-in.jsonld",
        expect="compact/p006-out.jsonld",
        context="compact/p006-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p007-in.jsonld",
        expect="compact/p007-out.jsonld",
        context="compact/p007-context.jsonld",
    ),
    ContextTestCase(
        input="compact/p008-in.jsonld",
        expect="compact/p008-out.jsonld",
        context="compact/p008-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pi01-in.jsonld",
        expect="compact/pi01-out.jsonld",
        context="compact/pi01-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pi02-in.jsonld",
        expect="compact/pi02-out.jsonld",
        context="compact/pi02-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pi03-in.jsonld",
        expect="compact/pi03-out.jsonld",
        context="compact/pi03-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pi04-in.jsonld",
        expect="compact/pi04-out.jsonld",
        context="compact/pi04-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pi05-in.jsonld",
        expect="compact/pi05-out.jsonld",
        context="compact/pi05-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pi06-in.jsonld",
        expect="compact/pi06-out.jsonld",
        context="compact/pi06-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pr01-in.jsonld", context="compact/pr01-context.jsonld"
    ),
    ContextTestCase(
        input="compact/pr02-in.jsonld", context="compact/pr02-context.jsonld"
    ),
    ContextTestCase(
        input="compact/pr03-in.jsonld", context="compact/pr03-context.jsonld"
    ),
    ContextTestCase(
        input="compact/pr04-in.jsonld",
        expect="compact/pr04-out.jsonld",
        context="compact/pr04-context.jsonld",
    ),
    ContextTestCase(
        input="compact/pr05-in.jsonld",
        expect="compact/pr05-out.jsonld",
        context="compact/pr05-context.jsonld",
    ),
    ContextTestCase(
        input="compact/r001-in.jsonld",
        expect="compact/r001-out.jsonld",
        context="compact/r001-context.jsonld",
    ),
    ContextTestCase(
        input="compact/r002-in.jsonld",
        expect="compact/r002-out.jsonld",
        context="compact/r002-context.jsonld",
    ),
    ContextTestCase(
        input="compact/s001-in.jsonld",
        expect="compact/s001-out.jsonld",
        context="compact/s001-context.jsonld",
    ),
    ContextTestCase(
        input="compact/s002-in.jsonld",
        expect="compact/s002-out.jsonld",
        context="compact/s002-context.jsonld",
    ),
    ContextTestCase(
        input="compact/tn01-in.jsonld",
        expect="compact/tn01-out.jsonld",
        context="compact/tn01-context.jsonld",
    ),
    ContextTestCase(
        input="compact/tn02-in.jsonld",
        expect="compact/tn02-out.jsonld",
        context="compact/tn02-context.jsonld",
    ),
    ContextTestCase(
        input="compact/tn03-in.jsonld",
        expect="compact/tn03-out.jsonld",
        context="compact/tn03-context.jsonld",
    ),
]
